/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ArenaManagerPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian6 = require("obsidian");

// lib/Settings.ts
var import_obsidian = require("obsidian");

// lib/types.ts
var ARENA_BLOCK_URL = "https://www.are.na/block/";
var ARENA_APP_URL = "https://are.na/developers";

// lib/Settings.ts
var DOWNLOAD_ATTACHMENTS_TYPES = {
  none: "1",
  channel: "2",
  custom: "3"
};
var CUSTOM_ATTACHMENTS_FOLDER = "arena/attachments";
var DEFAULT_SETTINGS = {
  accessToken: "",
  username: "",
  folder: "arena",
  attachments_folder: CUSTOM_ATTACHMENTS_FOLDER,
  download_attachments_type: DOWNLOAD_ATTACHMENTS_TYPES.none
};
var ArenaManagerSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(plugin) {
    super(plugin.app, plugin);
    this.plugin = plugin;
    this.plugin = plugin;
  }
  display() {
    this.containerEl.empty();
    this.addFolder();
    this.addUsername();
    this.addAccessToken();
    this.addSelect();
    if (this.plugin.settings.download_attachments_type !== DOWNLOAD_ATTACHMENTS_TYPES.none) {
      this.addAttachmentsFolder();
    }
  }
  addFolder() {
    new import_obsidian.Setting(this.containerEl).setName("Folder").setDesc("The folder where the blocks will be saved.").addText(
      (text) => text.setPlaceholder("Enter a name").setValue(this.plugin.settings.folder).onChange(async (value) => {
        this.plugin.settings.folder = value;
        await this.plugin.saveSettings();
      })
    );
  }
  addUsername() {
    new import_obsidian.Setting(this.containerEl).setName("Username").setDesc("Your are.na slug (e.g. 'username' in are.na/username).").addText(
      (text) => text.setPlaceholder("Enter your username").setValue(this.plugin.settings.username).onChange(async (value) => {
        this.plugin.settings.username = value;
        await this.plugin.saveSettings();
      })
    );
  }
  addAccessToken() {
    new import_obsidian.Setting(this.containerEl).setName("Access token").setDesc(
      createFragment((fragment) => {
        fragment.append(
          "Create an app with read and write access and get the 'Personal Access Token' from ",
          fragment.createEl("a", {
            text: ARENA_APP_URL,
            href: ARENA_APP_URL
          })
        );
      })
    ).addText(
      (text) => text.setPlaceholder("Enter your token").setValue(this.plugin.settings.accessToken).onChange(async (value) => {
        this.plugin.settings.accessToken = value;
        await this.plugin.saveSettings();
      })
    );
  }
  addSelect() {
    new import_obsidian.Setting(this.containerEl).setName("Download attachments and images").setDesc(
      "Choose where to download attachments and images for offline use."
    ).addDropdown((dropdown) => {
      dropdown.addOption(
        DOWNLOAD_ATTACHMENTS_TYPES.none,
        "Don't download (embed remote image URLs)"
      );
      dropdown.addOption(
        DOWNLOAD_ATTACHMENTS_TYPES.channel,
        "Download inside the channel folder"
      );
      dropdown.addOption(
        DOWNLOAD_ATTACHMENTS_TYPES.custom,
        "Download to a custom folder"
      );
      dropdown.setValue(
        this.plugin.settings.download_attachments_type
      );
      dropdown.onChange(async (value) => {
        this.plugin.settings.download_attachments_type = value;
        if (value === DOWNLOAD_ATTACHMENTS_TYPES.none) {
          this.plugin.settings.attachments_folder = void 0;
        } else if (value === DOWNLOAD_ATTACHMENTS_TYPES.channel) {
          this.plugin.settings.attachments_folder = void 0;
        } else if (value === DOWNLOAD_ATTACHMENTS_TYPES.custom) {
          this.plugin.settings.attachments_folder = CUSTOM_ATTACHMENTS_FOLDER;
        }
        await this.plugin.saveSettings();
        this.display();
      });
    });
  }
  addAttachmentsFolder() {
    let name = "Channel attachments folder";
    let tooltip = createFragment((fragment) => {
      fragment.append(
        "Save inside the channel folder:",
        fragment.createEl("code", {
          text: `${this.plugin.settings.folder}/channel/{folder name}.`
        })
      );
      fragment.append(
        "Leave empty to save directly in the channel folder"
      );
    });
    if (this.plugin.settings.download_attachments_type === DOWNLOAD_ATTACHMENTS_TYPES.custom) {
      name = "Custom attachments folder";
      tooltip = tooltip = createFragment((fragment) => {
        fragment.append(
          "Save inside a custom folder:",
          fragment.createEl("code", {
            text: `${this.plugin.settings.folder}/attachments/{folder name}.`
          })
        );
      });
    }
    new import_obsidian.Setting(this.containerEl).setName(name).setDesc(tooltip).addText(
      (text) => text.setPlaceholder("Folder name").setValue(this.plugin.settings.attachments_folder || "").onChange(async (value) => {
        this.plugin.settings.attachments_folder = value;
        await this.plugin.saveSettings();
      })
    );
  }
};

// lib/Commands.ts
var import_obsidian5 = require("obsidian");

// lib/Arena.ts
var import_obsidian2 = require("obsidian");

// lib/normalize.ts
function decodeEntities(text) {
  return text.replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&amp;/g, "&");
}
function deriveTitle(markdown) {
  if (!markdown) {
    return "Untitled";
  }
  const firstLine = markdown.replace(/\s+/g, " ").trim().slice(0, 50).trim();
  return firstLine || "Untitled";
}
function normalizeBlock(raw) {
  var _a, _b, _c, _d, _e, _f, _g, _h, _i, _j, _k, _l;
  const title = (_a = raw.title) != null ? _a : "";
  const block = {
    id: raw.id,
    class: raw.type,
    title,
    // content is HTML-decoded by v3; old (pre-migration) descriptions are not,
    // so we decode them to keep markdown (blockquotes, `&`, `<`) intact.
    content: (_c = (_b = raw.content) == null ? void 0 : _b.markdown) != null ? _c : "",
    description: decodeEntities((_e = (_d = raw.description) == null ? void 0 : _d.markdown) != null ? _e : ""),
    // v2 always populated generated_title and several call sites use it
    // directly as a file name. v3 dropped it, so we always provide a usable
    // value: the real title when present, otherwise one derived from content.
    generated_title: title || deriveTitle((_f = raw.content) == null ? void 0 : _f.markdown),
    position: (_h = (_g = raw.connection) == null ? void 0 : _g.position) != null ? _h : 0
  };
  if (raw.image) {
    block.image = {
      display: { url: (_j = (_i = raw.image.large) == null ? void 0 : _i.src) != null ? _j : raw.image.src },
      // Kept so images can be downloaded locally with a sensible extension
      // (the display URL is a resized CDN link with no file extension).
      filename: raw.image.filename,
      content_type: raw.image.content_type
    };
  }
  if (raw.attachment) {
    block.attachment = {
      file_name: raw.attachment.filename,
      extension: raw.attachment.file_extension,
      file_size: raw.attachment.file_size,
      url: raw.attachment.url
    };
  }
  if ((_k = raw.embed) == null ? void 0 : _k.html) {
    block.embed = { html: raw.embed.html };
  }
  if ((_l = raw.user) == null ? void 0 : _l.slug) {
    block.user = { slug: raw.user.slug };
  }
  if (raw.source) {
    block.source = { title: raw.source.title, url: raw.source.url };
  }
  return block;
}
function normalizeChannel(raw) {
  var _a, _b, _c;
  return {
    id: raw.id,
    slug: raw.slug,
    title: (_a = raw.title) != null ? _a : "",
    length: (_c = (_b = raw.counts) == null ? void 0 : _b.blocks) != null ? _c : 0,
    status: raw.visibility
  };
}

// lib/Arena.ts
var PER_PAGE = 100;
function getErrorMessage(response) {
  try {
    const body = response.json;
    if (body == null ? void 0 : body.message)
      return body.message;
    if (body == null ? void 0 : body.title)
      return body.title;
  } catch (e) {
  }
  return `Request failed with status ${response.status}`;
}
var Arena = class {
  constructor(settings) {
    this.settings = settings;
  }
  // Defaults to the signed-in user, but accepts any username so the picker can
  // browse another user's channels. The token only ever sees channels it has
  // access to, so private channels of other users simply don't come back.
  async getChannelsFromUser(username = this.settings.username) {
    var _a, _b;
    const baseUrl = `https://api.are.na/v3/users/${username}/contents`;
    const headers = {
      Authorization: `Bearer ${this.settings.accessToken}`
    };
    const channels = [];
    let page = 1;
    let hasMorePages = true;
    while (hasMorePages) {
      const url = `${baseUrl}?type=Channel&page=${page}&per=${PER_PAGE}&v=${Date.now()}`;
      try {
        const response = await (0, import_obsidian2.requestUrl)({ url, headers });
        if (response.status !== 200) {
          throw new Error(`HTTP error! Status: ${response.status}`);
        }
        const data = response.json;
        for (const raw of data.data) {
          channels.push(normalizeChannel(raw));
        }
        hasMorePages = (_b = (_a = data.meta) == null ? void 0 : _a.has_more_pages) != null ? _b : false;
        page += 1;
      } catch (error) {
        console.error("Error fetching channels:", error);
        break;
      }
    }
    return channels;
  }
  // Resolve a single channel by slug (or numeric id), used when the user pastes
  // a channel URL. v3 returns the channel object directly, not wrapped in `data`.
  async getChannel(slug) {
    const response = await (0, import_obsidian2.requestUrl)({
      url: `https://api.are.na/v3/channels/${slug}?v=${Date.now()}`,
      throw: false,
      headers: {
        Authorization: `Bearer ${this.settings.accessToken}`
      }
    });
    if (response.status >= 400) {
      throw new Error(getErrorMessage(response));
    }
    return normalizeChannel(response.json);
  }
  async updateBlockWithContentAndBlockID(id, title, content, frontmatter = {}) {
    const newTitle = typeof frontmatter.title === "string" ? frontmatter.title : title;
    const description = frontmatter.description;
    content = content.replace(/^---\n[\s\S]*?\n---\n/, "");
    const response = await (0, import_obsidian2.requestUrl)({
      url: `https://api.are.na/v3/blocks/${id}`,
      method: "PUT",
      throw: false,
      headers: {
        Authorization: `Bearer ${this.settings.accessToken}`,
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        title: newTitle,
        content,
        description
      })
    });
    if (response.status >= 400) {
      throw new Error(getErrorMessage(response));
    }
    return response.json;
  }
  async getBlockWithID(id) {
    const url = `https://api.are.na/v3/blocks/${id}?v=${Date.now()}`;
    return (0, import_obsidian2.requestUrl)({
      url,
      headers: {
        Authorization: `Bearer ${this.settings.accessToken}`
      }
    }).then((response) => response.json).then((data) => normalizeBlock(data));
  }
  async getBlocksFromChannel(channelSlug) {
    var _a, _b;
    const headers = {
      Authorization: `Bearer ${this.settings.accessToken}`
    };
    const blocks = [];
    let page = 1;
    let hasMorePages = true;
    while (hasMorePages) {
      const url = `https://api.are.na/v3/channels/${channelSlug}/contents?page=${page}&per=${PER_PAGE}&v=${Date.now()}`;
      const response = await (0, import_obsidian2.requestUrl)({ url, headers });
      if (response.status !== 200) {
        throw new Error(`HTTP error! Status: ${response.status}`);
      }
      const data = response.json;
      for (const raw of data.data) {
        blocks.push(normalizeBlock(raw));
      }
      hasMorePages = (_b = (_a = data.meta) == null ? void 0 : _a.has_more_pages) != null ? _b : false;
      page += 1;
    }
    return blocks.sort((a, b) => b.position - a.position);
  }
  async createBlockWithContentAndTitle(content, generated_title, channelSlug, frontmatter = {}) {
    const title = frontmatter.title || generated_title;
    const description = frontmatter.description;
    content = content.replace(/^---\n[\s\S]*?\n---\n/, "");
    const response = await (0, import_obsidian2.requestUrl)({
      url: `https://api.are.na/v3/blocks`,
      method: "POST",
      throw: false,
      headers: {
        Authorization: `Bearer ${this.settings.accessToken}`,
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        value: content,
        title,
        description,
        channel_ids: [channelSlug]
      })
    });
    if (response.status >= 400) {
      throw new Error(getErrorMessage(response));
    }
    return response.json;
  }
};

// lib/FileHandler.ts
var import_obsidian3 = require("obsidian");
var MAX_FILENAME_LENGTH = 200;
var Filemanager = class {
  constructor(app, settings) {
    this.app = app;
    this.settings = settings;
  }
  getSafeFilename(fileName) {
    const safe = fileName.replace(/[\\/:*?"<>|#^[\]]/g, " ").replace(/\s+/g, " ").trim();
    return this.truncateFilename(safe || "Untitled");
  }
  // Clamp an over-long name to MAX_FILENAME_LENGTH, preserving a short trailing
  // extension (e.g. ".png") when present so truncated attachment names keep a
  // valid type. Longer tails after the final dot are treated as prose, not an
  // extension, and simply cut.
  truncateFilename(name) {
    if (name.length <= MAX_FILENAME_LENGTH) {
      return name;
    }
    const dotIndex = name.lastIndexOf(".");
    const hasExtension = dotIndex > 0 && name.length - dotIndex <= 6;
    const extension = hasExtension ? name.slice(dotIndex) : "";
    const stem = hasExtension ? name.slice(0, dotIndex) : name;
    return stem.slice(0, MAX_FILENAME_LENGTH - extension.length) + extension;
  }
  // Block ids round-trip through YAML frontmatter, where they can come back as
  // either a number (freshly written) or a string (manual edits, quoting, older
  // notes — note getFilesWithBlockId coerces with Number() for the same reason).
  // A strict `===` would treat "123" and 123 as different blocks and re-create
  // the note on every sync, so compare them numerically.
  sameBlockId(a, b) {
    if (a == null || a === "" || b == null || b === "") {
      return false;
    }
    const na = Number(a);
    const nb = Number(b);
    return Number.isFinite(na) && Number.isFinite(nb) && na === nb;
  }
  async doesAttachmentExist(fileName) {
    const filePath = `${this.settings.attachments_folder}/${fileName}`;
    return this.doesFileExist(filePath);
  }
  async doesFileExist(filePath) {
    const file = this.app.vault.getAbstractFileByPath(filePath);
    return file !== null;
  }
  async renameFile(filePath, title, content, frontData = {}, attachment) {
    const fileName = this.getSafeFilename(title);
    let folderPath = this.settings.folder;
    if (frontData.channel) {
      folderPath = `${folderPath}/${frontData.channel}`;
    }
    if (this.settings.download_attachments_type !== DOWNLOAD_ATTACHMENTS_TYPES.none && attachment) {
      const attachmentFileName = await this.downloadAttachment(
        attachment,
        folderPath,
        fileName,
        frontData.blockid
      );
      if (attachmentFileName) {
        content = `![[${attachmentFileName}]]`;
      }
    }
    const newName = `${folderPath}/${fileName}.md`;
    await this.app.vault.modify(filePath, content);
    await this.writeFrontmatter(filePath, frontData);
    await this.app.vault.rename(filePath, newName);
  }
  getFileByFolderPathAndFileName(folderPath, fileName) {
    const normalizedFolderPath = folderPath.replace(/\\/g, "/");
    const filePath = `${normalizedFolderPath}/${this.getSafeFilename(fileName)}.md`;
    return this.app.vault.getFileByPath(filePath);
  }
  async createFolder(folderPath) {
    const normalizedFolderPath = folderPath.replace(/\\/g, "/");
    const folder = this.app.vault.getAbstractFileByPath(normalizedFolderPath);
    if (!folder) {
      await this.app.vault.createFolder(normalizedFolderPath);
    }
  }
  async updateFileWithFrontmatter(folderPath, fileName, content, frontData = {}) {
    const normalizedFolderPath = folderPath.replace(/\\/g, "/");
    const filePath = `${normalizedFolderPath}/${this.getSafeFilename(fileName)}.md`;
    const file = this.app.vault.getFileByPath(filePath);
    if (file) {
      await this.app.vault.modify(file, content);
      await this.writeFrontmatter(file, frontData);
    }
  }
  async createFileWithFrontmatter(folderPath, fileName, content, frontData = {}) {
    const normalizedFolderPath = folderPath.replace(/\\/g, "/");
    const filePath = `${normalizedFolderPath}/${this.getSafeFilename(fileName)}.md`;
    const file = await this.app.vault.create(filePath, content);
    await this.writeFrontmatter(file, frontData);
  }
  getAttachmentFilenameFromTitle(attachment, title, blockId) {
    let name = title || attachment.file_name;
    if (name.endsWith(`.${attachment.extension}`)) {
      name = name.slice(0, -attachment.extension.length - 1);
    }
    if (blockId != null && blockId !== "") {
      name = `${name}-${blockId}`;
    }
    return this.getSafeFilename(`${name}.${attachment.extension}`);
  }
  async downloadAttachment(attachment, folderPath, filename, blockId) {
    const request = await (0, import_obsidian3.requestUrl)(attachment.url);
    if (this.settings.download_attachments_type != DOWNLOAD_ATTACHMENTS_TYPES.none && this.settings.attachments_folder) {
      if (this.settings.download_attachments_type == DOWNLOAD_ATTACHMENTS_TYPES.channel) {
        await this.createFolder(
          `${folderPath}/${this.settings.attachments_folder}`
        );
      } else if (this.settings.download_attachments_type == DOWNLOAD_ATTACHMENTS_TYPES.custom) {
        await this.createFolder(this.settings.attachments_folder);
      }
    }
    try {
      const attachmentFileName = this.getAttachmentFilenameFromTitle(
        attachment,
        filename,
        blockId
      );
      let attachmentFolderPath = this.settings.attachments_folder;
      if (this.settings.download_attachments_type == DOWNLOAD_ATTACHMENTS_TYPES.channel) {
        if (this.settings.attachments_folder) {
          attachmentFolderPath = `${folderPath}/${this.settings.attachments_folder}`;
        } else {
          attachmentFolderPath = `${folderPath}`;
        }
      }
      await this.app.vault.adapter.writeBinary(
        `${attachmentFolderPath}/${attachmentFileName}`,
        request.arrayBuffer
      );
      if (this.settings.download_attachments_type == DOWNLOAD_ATTACHMENTS_TYPES.channel) {
        if (this.settings.attachments_folder) {
          return `${folderPath}/${this.settings.attachments_folder}/${attachmentFileName}`;
        } else {
          return `${folderPath}/${attachmentFileName}`;
        }
      } else {
        return `${attachmentFolderPath}/${attachmentFileName}`;
      }
    } catch (error) {
      console.error("Error downloading attachment", error);
      return null;
    }
  }
  async findNextAvailableFileName(folderPath, baseFileName, blockId) {
    baseFileName = this.getSafeFilename(baseFileName);
    let counter = 0;
    let filePath = `${folderPath}/${baseFileName}.md`;
    while (await this.doesFileExist(filePath)) {
      const file = this.app.vault.getAbstractFileByPath(filePath);
      if (file instanceof import_obsidian3.TFile) {
        const frontmatter = await this.getFrontmatterFromFile(file);
        if (this.sameBlockId(frontmatter.blockid, blockId)) {
          if (counter === 0) {
            return baseFileName;
          } else {
            return `${baseFileName}-${counter}`;
          }
        }
      }
      counter++;
      filePath = `${folderPath}/${baseFileName}-${counter}.md`;
    }
    return `${baseFileName}-${counter}`;
  }
  async updateFile(file, folderPath, fileName, content, frontData = {}, attachment) {
    const blockId = await this.getBlockIdFromFile(file);
    if (this.sameBlockId(blockId, frontData == null ? void 0 : frontData.blockid)) {
      if (this.settings.download_attachments_type !== DOWNLOAD_ATTACHMENTS_TYPES.none && attachment) {
        const attachmentFileName = await this.downloadAttachment(
          attachment,
          folderPath,
          fileName,
          frontData.blockid
        );
        if (attachmentFileName) {
          content = `![[${attachmentFileName}]]`;
        }
      }
      await this.updateFileWithFrontmatter(
        folderPath,
        fileName,
        content,
        frontData
      );
    } else {
      const baseFileName = `${fileName.split(".")[0]}`;
      const newFilename = await this.findNextAvailableFileName(
        folderPath,
        baseFileName,
        frontData.blockid
      );
      if (this.settings.download_attachments_type !== DOWNLOAD_ATTACHMENTS_TYPES.none && attachment) {
        const attachmentFileName = await this.downloadAttachment(
          attachment,
          folderPath,
          newFilename,
          frontData.blockid
        );
        if (attachmentFileName) {
          content = `![[${attachmentFileName}]]`;
        }
      }
      const newFile = this.getFileByFolderPathAndFileName(
        folderPath,
        newFilename
      );
      if (!newFile) {
        await this.createFileWithFrontmatter(
          folderPath,
          newFilename,
          content,
          frontData
        );
      } else {
        await this.updateFileWithFrontmatter(
          folderPath,
          newFilename,
          content,
          frontData
        );
      }
    }
  }
  async writeFile(folderPath, fileName, content, frontData = {}, attachment) {
    await this.createFolder(folderPath);
    const file = this.getFileByFolderPathAndFileName(folderPath, fileName);
    if (!content) {
      content = "";
      console.warn("Empty content");
    }
    if (!file) {
      if (this.settings.download_attachments_type !== DOWNLOAD_ATTACHMENTS_TYPES.none && attachment) {
        const attachmentFileName = await this.downloadAttachment(
          attachment,
          folderPath,
          fileName,
          frontData.blockid
        );
        if (attachmentFileName) {
          content = `![[${attachmentFileName}]]`;
        }
      }
      await this.createFileWithFrontmatter(
        folderPath,
        fileName,
        content,
        frontData
      );
    } else {
      await this.updateFile(
        file,
        folderPath,
        fileName,
        content,
        frontData,
        attachment
      );
    }
  }
  async getFrontmatterFromFile(file) {
    let frontmatterData = {};
    await this.app.fileManager.processFrontMatter(
      file,
      (frontmatter) => {
        frontmatterData = frontmatter || null;
      }
    );
    return frontmatterData;
  }
  async getBlockIdFromFile(file) {
    let blockId = null;
    await this.app.fileManager.processFrontMatter(
      file,
      (frontmatter) => {
        blockId = frontmatter.blockid || null;
      }
    );
    return blockId;
  }
  async writeFrontmatter(file, frontData) {
    if (!frontData) {
      return;
    }
    await this.app.fileManager.processFrontMatter(
      file,
      (frontmatter) => {
        Object.entries(frontData).forEach(([key, value]) => {
          frontmatter[key] = value;
        });
      }
    );
  }
  isMarkdownFile(file) {
    return file instanceof import_obsidian3.TFile && file.extension === "md";
  }
  async getFilesWithBlockId(folderPath) {
    const result = [];
    const folder = this.app.vault.getAbstractFileByPath(folderPath);
    if (!folder || !(folder instanceof import_obsidian3.TFolder)) {
      throw new Error("Directory not found or not a folder");
    }
    const files = folder.children.filter(this.isMarkdownFile);
    for (const file of files) {
      await this.app.fileManager.processFrontMatter(
        file,
        (frontmatter) => {
          if (frontmatter.blockid) {
            const blockid = Number(frontmatter.blockid);
            if (!isNaN(blockid)) {
              result.push({
                name: file.name,
                blockid
              });
            } else {
              console.warn(
                `Invalid blockid for file ${file.name}: ${frontmatter.blockid}`
              );
            }
          }
        }
      );
    }
    return result;
  }
};

// lib/Utils.ts
var Utils = class {
  createPermalinkFromTitle(title) {
    return title.replace(/-\d+$/, "");
  }
  // Image and Link blocks have no usable markdown body; represent them as an
  // embedded image pointing at the block's display URL. Embed (Media) blocks
  // — YouTube, Vimeo, etc. — carry their iframe HTML, which Obsidian renders as
  // a playable embed in reading view. Everything else uses its own content.
  getBlockContent(block) {
    var _a, _b;
    if (block.class === "Image" || block.class === "Link") {
      return `![](${(_a = block.image) == null ? void 0 : _a.display.url})`;
    }
    if ((_b = block.embed) == null ? void 0 : _b.html) {
      return block.embed.html;
    }
    return block.content;
  }
  getBlockAttachment(block) {
    return block.class === "Attachment" ? block.attachment : void 0;
  }
  // The binary a note should embed locally when downloading is enabled: a real
  // Attachment block's file, or an Image/Link block's image. Returning an
  // Attachment-shaped descriptor lets images reuse the attachment download path
  // (which then rewrites the note body to `![[local file]]`).
  getDownloadable(block) {
    if (block.class === "Attachment") {
      return block.attachment;
    }
    if (block.class === "Image" || block.class === "Link") {
      return this.imageToAttachment(block);
    }
    return void 0;
  }
  imageToAttachment(block) {
    var _a, _b, _c;
    const url = (_a = block.image) == null ? void 0 : _a.display.url;
    if (!url) {
      return void 0;
    }
    const extension = this.getImageExtension(block.image);
    return {
      url,
      extension,
      file_name: (_c = (_b = block.image) == null ? void 0 : _b.filename) != null ? _c : `${block.id}.${extension}`,
      file_size: 0
    };
  }
  // are.na's display URL is a resized CDN link with no extension, so derive one
  // from the original filename, then the content type, falling back to jpg.
  getImageExtension(image) {
    var _a;
    const fromFilename = (_a = image == null ? void 0 : image.filename) == null ? void 0 : _a.split(".").pop();
    if (fromFilename && /^[a-z0-9]{1,5}$/i.test(fromFilename)) {
      return fromFilename.toLowerCase();
    }
    const contentType = image == null ? void 0 : image.content_type;
    if (contentType == null ? void 0 : contentType.startsWith("image/")) {
      const subtype = contentType.slice("image/".length).replace("+xml", "");
      return subtype === "jpeg" ? "jpg" : subtype;
    }
    return "jpg";
  }
  getFrontmatterFromBlock(block, channelTitle) {
    var _a, _b, _c;
    const frontmatter = {};
    frontmatter["blockid"] = block.id;
    if (block.class) {
      frontmatter["class"] = block.class;
    }
    if (block.title) {
      frontmatter["title"] = block.title;
    }
    if (block.description) {
      frontmatter["description"] = block.description;
    }
    if ((_a = block.user) == null ? void 0 : _a.slug) {
      frontmatter["user"] = block.user.slug;
    }
    if ((_b = block.source) == null ? void 0 : _b.title) {
      frontmatter["source title"] = block.source.title;
    }
    if ((_c = block.source) == null ? void 0 : _c.url) {
      frontmatter["source url"] = block.source.url;
    }
    if (channelTitle) {
      frontmatter["channel"] = channelTitle;
    }
    return frontmatter;
  }
  hasRequiredSettings(settings) {
    const { username, folder, accessToken } = settings;
    if (!username || !folder || !accessToken) {
      return false;
    }
    return true;
  }
};
var Utils_default = new Utils();

// lib/Modals.ts
var import_obsidian4 = require("obsidian");
var INSTRUCTIONS = [
  { command: "\u2191\u2193", purpose: "to navigate" },
  { command: "Tab \u21B9", purpose: "to autocomplete" },
  { command: "\u21B5", purpose: "to choose item" },
  { command: "esc", purpose: "to dismiss" }
];
var SOURCE_INSTRUCTIONS = [
  { command: "\u2191\u2193", purpose: "to navigate" },
  { command: "\u21B5", purpose: "to choose item" },
  { command: "esc", purpose: "to dismiss" }
];
var ChannelSourceModal = class extends import_obsidian4.FuzzySuggestModal {
  constructor(app, username, callback) {
    super(app);
    this.callback = callback;
    this.options = [
      { id: "your-channels", label: `Your channels (@${username})` },
      { id: "other-user", label: "Channels from another user" },
      { id: "channel-url", label: "Channel URL" }
    ];
    this.setInstructions(SOURCE_INSTRUCTIONS);
    this.containerEl.addClass("arena-manager-modal");
    this.containerEl.addClass("arena-manager-no-search");
  }
  // Always show every option: with the search field hidden there's no way to
  // type a query, and this keeps the list full even if a stray keystroke lands
  // on the (invisible) input.
  getSuggestions(_query) {
    return this.options.map((item) => ({
      item,
      match: { score: 0, matches: [] }
    }));
  }
  getItems() {
    return this.options;
  }
  getItemText(option) {
    return option.label;
  }
  onChooseItem(option, _evt) {
    this.callback(option.id);
  }
};
var ChannelsModal = class extends import_obsidian4.FuzzySuggestModal {
  constructor(app, settings, showEmptyChannels, events, callback, username = settings.username) {
    super(app);
    this.settings = settings;
    this.events = events;
    this.showEmptyChannels = showEmptyChannels;
    this.callback = callback;
    this.emptyStateText = "No channels found. Press esc to dismiss.";
    this.setPlaceholder(`Search @${username}'s channels`);
    this.containerEl.addClass("arena-manager-modal");
  }
  onOpen() {
    const $prompt = this.containerEl.querySelector(".prompt-results");
    if ($prompt) {
      $prompt.addClass("is-loading");
    }
    this.events.on("channels-load", (channels) => {
      this.channels = channels;
      if ($prompt) {
        $prompt.removeClass("is-loading");
      }
      this.setInstructions(INSTRUCTIONS);
      void super.onOpen();
    });
  }
  renderSuggestion(match, el) {
    if (match.item.status === "private") {
      el.createSpan({ cls: "icon-lock" });
    }
    el.createSpan({ text: match.item.title });
    el.createSpan({ text: match.item.length.toString() }).addClass("count");
  }
  getItems() {
    if (this.showEmptyChannels) {
      return this.channels;
    } else if (this.channels) {
      return this.channels.filter((channel) => channel.length > 0);
    } else {
      return [];
    }
  }
  getItemText(channel) {
    return `${channel.title} (${channel.length})`;
  }
  onChooseItem(channel, _evt) {
    this.callback(channel);
  }
};
var BlocksModal = class extends import_obsidian4.FuzzySuggestModal {
  constructor(app, channel, events, callback) {
    super(app);
    this.blocks = [];
    this.channel = channel;
    this.events = events;
    this.callback = callback;
    this.emptyStateText = "No blocks found. Press esc to dismiss.";
    this.setPlaceholder(`Search blocks from ${channel.title}`);
    this.emptyStateText = "Loading...";
  }
  onOpen() {
    const $prompt = this.containerEl.querySelector(".prompt-results");
    if ($prompt) {
      $prompt.addClass("is-loading");
    }
    this.events.on("blocks-load", (blocks) => {
      this.blocks = blocks;
      if ($prompt) {
        $prompt.removeClass("is-loading");
      }
      this.setInstructions(INSTRUCTIONS);
      void super.onOpen();
    });
  }
  getItems() {
    if (this.blocks) {
      return this.blocks.filter((block) => block.class !== "Channel");
    }
    return this.blocks;
  }
  getItemText(item) {
    return item.generated_title;
  }
  onChooseItem(block, _evt) {
    this.callback(block, this.channel);
  }
};
var InputModal = class extends import_obsidian4.SuggestModal {
  constructor(app, onSubmit, options = {}) {
    var _a, _b;
    super(app);
    this.submitting = false;
    this.onSubmit = onSubmit;
    this.setPlaceholder(
      (_a = options.placeholder) != null ? _a : "Enter an are.na block URL or ID"
    );
    this.setInstructions([
      { command: "\u21B5", purpose: "to submit" },
      { command: "esc", purpose: "to dismiss" }
    ]);
    this.containerEl.addClass("arena-manager-modal");
    this.containerEl.addClass("arena-manager-input-only");
    this.statusEl = createDiv({ cls: "arena-manager-input-status" });
    const inputRow = (_b = this.inputEl.parentElement) != null ? _b : this.inputEl;
    inputRow.insertAdjacentElement("afterend", this.statusEl);
    this.inputEl.addEventListener("input", () => this.clearStatus());
  }
  clearStatus() {
    this.statusEl.setText("");
    this.statusEl.removeClasses(["is-error", "is-loading"]);
  }
  showError(message) {
    this.statusEl.setText(message);
    this.statusEl.removeClass("is-loading");
    this.statusEl.addClass("is-error");
  }
  showLoading() {
    this.statusEl.setText("Checking\u2026");
    this.statusEl.removeClass("is-error");
    this.statusEl.addClass("is-loading");
  }
  async handleSubmit() {
    if (this.submitting) {
      return;
    }
    const value = this.inputEl.value;
    const outcome = this.onSubmit(value);
    if (!(outcome instanceof Promise)) {
      if (outcome) {
        this.showError(outcome);
      } else {
        this.close();
      }
      return;
    }
    this.submitting = true;
    this.showLoading();
    try {
      const error = await outcome;
      if (error) {
        this.showError(error);
      } else {
        this.close();
      }
    } finally {
      this.submitting = false;
    }
  }
  getSuggestions(query) {
    return [query];
  }
  renderSuggestion(_value, _el) {
  }
  // SuggestModal closes the modal right after choosing a suggestion. We override
  // the choose step so submission is validated first and only closes on success.
  selectSuggestion(_value, _evt) {
    void this.handleSubmit();
  }
  onChooseSuggestion(_value, _evt) {
  }
};

// lib/Commands.ts
function getIDFromURL(url) {
  const blockMatch = url.match(/block\/(\d+)/);
  if (blockMatch) {
    return Number(blockMatch[1]);
  }
  if (/^\d+$/.test(url)) {
    return Number(url);
  }
  return null;
}
function getSlugFromURL(input) {
  let value = input.trim();
  if (!value) {
    return null;
  }
  if (/\bblock\/\d+/.test(value) || /^\d+$/.test(value)) {
    return null;
  }
  value = value.split(/[?#]/)[0].replace(/\/+$/, "");
  const slug = value.substring(value.lastIndexOf("/") + 1);
  return slug || null;
}
var Commands = class {
  constructor(app, settings) {
    this.app = app;
    this.settings = settings;
    this.arena = new Arena(settings);
    this.fileHandler = new Filemanager(app, settings);
  }
  async pushBlock() {
    const currentFile = this.app.workspace.getActiveFile();
    if (!currentFile) {
      new import_obsidian5.Notice("Open a note to push it to are.na.");
      return;
    }
    const currentFileContent = await this.app.vault.read(currentFile);
    void this.app.fileManager.processFrontMatter(currentFile, (frontmatter) => {
      const blockId = frontmatter.blockid;
      if (blockId) {
        const title = currentFile.basename;
        if (frontmatter.user !== this.settings.username) {
          new import_obsidian5.Notice(
            `You don't have permission to update ${frontmatter.user}'s block`
          );
          return;
        }
        void this.arena.updateBlockWithContentAndBlockID(
          blockId,
          title,
          currentFileContent,
          frontmatter
        ).then(() => {
          new import_obsidian5.Notice("Block updated");
        }).catch((error) => {
          console.error(error);
          new import_obsidian5.Notice(`Block not updated: ${error.message}`);
        });
      } else {
        const events = new import_obsidian5.Events();
        const onSelectChannel = (channel) => {
          void this.arena.createBlockWithContentAndTitle(
            currentFileContent,
            currentFile.basename,
            channel.slug,
            frontmatter
          ).then((response) => {
            void this.app.fileManager.processFrontMatter(
              currentFile,
              (fm) => {
                fm["blockid"] = response.id;
                fm["channel"] = Utils_default.createPermalinkFromTitle(
                  channel.title
                );
              }
            );
            new import_obsidian5.Notice("Block created");
          }).catch((error) => {
            console.error(error);
            new import_obsidian5.Notice(`Block not created: ${error.message}`);
          });
        };
        new ChannelsModal(
          this.app,
          this.settings,
          true,
          events,
          onSelectChannel
        ).open();
        void this.arena.getChannelsFromUser().then((channels) => {
          events.trigger("channels-load", channels);
        }).catch((error) => {
          console.error(error);
          new import_obsidian5.Notice("Couldn't load your channels.");
        });
      }
    });
  }
  // Ask where the channel should come from (your channels, another user's
  // channels, or a pasted channel URL), then hand the resolved channel to
  // `onResolve`. Shared by getBlocksFromChannel and getBlockFromArena.
  resolveChannel(onResolve) {
    new ChannelSourceModal(
      this.app,
      this.settings.username,
      (source) => {
        if (source === "your-channels") {
          this.openChannelPicker(this.settings.username, onResolve);
        } else if (source === "other-user") {
          this.openOtherUserChannelPicker(onResolve);
        } else {
          this.openChannelFromURL(onResolve);
        }
      }
    ).open();
  }
  // Fuzzy-pick a channel from a given user's (accessible) channels.
  openChannelPicker(username, onResolve) {
    const events = new import_obsidian5.Events();
    new ChannelsModal(
      this.app,
      this.settings,
      false,
      events,
      onResolve,
      username
    ).open();
    void this.arena.getChannelsFromUser(username).then((channels) => {
      events.trigger("channels-load", channels);
    }).catch((error) => {
      console.error(error);
      new import_obsidian5.Notice(`Couldn't load @${username}'s channels.`);
    });
  }
  // Prompt for a username, then pick from that user's channels.
  openOtherUserChannelPicker(onResolve) {
    new InputModal(
      this.app,
      (value) => {
        const username = value.trim().replace(/^@/, "");
        if (!username) {
          return "Enter an are.na username.";
        }
        this.openChannelPicker(username, onResolve);
        return null;
      },
      {
        placeholder: "Enter an are.na username"
      }
    ).open();
  }
  // Prompt for a channel URL (or slug) and resolve it directly.
  openChannelFromURL(onResolve) {
    new InputModal(
      this.app,
      (value) => {
        const slug = getSlugFromURL(value);
        if (!slug) {
          return "That doesn't look like an are.na channel URL.";
        }
        return this.arena.getChannel(slug).then((channel) => {
          onResolve(channel);
          return null;
        }).catch((error) => {
          console.error(error);
          return "Couldn't find that channel. Check the URL and try again.";
        });
      },
      {
        placeholder: "Enter an are.na channel URL"
      }
    ).open();
  }
  async getBlocksFromChannel() {
    this.resolveChannel((channel) => this.importBlocksFromChannel(channel));
  }
  importBlocksFromChannel(channel) {
    let notesCreated = 0;
    let failed = 0;
    new import_obsidian5.Notice(`Getting blocks from ${channel.title}\u2026`);
    void this.arena.getBlocksFromChannel(channel.slug).then(async (blocks) => {
      for (const block of blocks) {
        if (block.class === "Channel") {
          continue;
        }
        const fileName = block.generated_title ? block.generated_title : block.title;
        const frontData = Utils_default.getFrontmatterFromBlock(
          block,
          channel.title
        );
        const slug = Utils_default.createPermalinkFromTitle(channel.title);
        const content = Utils_default.getBlockContent(block);
        try {
          await this.fileHandler.writeFile(
            `${this.settings.folder}/${slug}`,
            fileName,
            content,
            frontData,
            Utils_default.getDownloadable(block)
          );
          notesCreated++;
        } catch (error) {
          console.error(error);
          failed++;
        }
      }
      const saved = `${notesCreated} note${notesCreated !== 1 ? "s" : ""} saved`;
      new import_obsidian5.Notice(failed ? `${saved}, ${failed} failed` : saved);
    }).catch((error) => {
      console.error(error);
      new import_obsidian5.Notice(`Couldn't get blocks from ${channel.title}.`);
    });
  }
  async pullBlock() {
    const currentFile = this.app.workspace.getActiveFile();
    if (!currentFile) {
      new import_obsidian5.Notice("Open a note to pull it from are.na.");
      return;
    }
    const frontMatter = await this.fileHandler.getFrontmatterFromFile(currentFile);
    const blockId = frontMatter == null ? void 0 : frontMatter.blockid;
    if (blockId) {
      void this.arena.getBlockWithID(blockId).then(async (block) => {
        const title = block.generated_title;
        const channelTitle = frontMatter == null ? void 0 : frontMatter.channel;
        const frontData = Utils_default.getFrontmatterFromBlock(
          block,
          channelTitle
        );
        const content = Utils_default.getBlockContent(block);
        await this.fileHandler.renameFile(
          currentFile,
          title,
          content,
          frontData,
          Utils_default.getDownloadable(block)
        );
        new import_obsidian5.Notice("Note updated");
      }).catch((error) => {
        console.error(error);
        new import_obsidian5.Notice(`Couldn't pull block: ${error.message}`);
      });
    } else {
      new import_obsidian5.Notice("No block id found in frontmatter");
    }
  }
  async goToBlock() {
    const currentFile = this.app.workspace.getActiveFile();
    if (!currentFile) {
      new import_obsidian5.Notice("Open a note to go to its block on are.na.");
      return;
    }
    void this.app.fileManager.processFrontMatter(
      currentFile,
      (frontmatter) => {
        const blockId = frontmatter.blockid;
        if (blockId) {
          const url = `${ARENA_BLOCK_URL}${blockId}`;
          window.open(url, "_blank");
        } else {
          new import_obsidian5.Notice("No block id found in frontmatter");
        }
      }
    );
  }
  async getBlockFromArena() {
    this.resolveChannel((channel) => this.pickBlockFromChannel(channel));
  }
  pickBlockFromChannel(channel) {
    const events = new import_obsidian5.Events();
    const onSelectBlock = (block, channel2) => {
      const fileName = `${block.generated_title}`;
      const frontData = Utils_default.getFrontmatterFromBlock(
        block,
        channel2.title
      );
      const slug = Utils_default.createPermalinkFromTitle(channel2.title);
      const content = Utils_default.getBlockContent(block);
      void this.fileHandler.writeFile(
        `${this.settings.folder}/${slug}`,
        fileName,
        content,
        frontData,
        Utils_default.getDownloadable(block)
      ).then(() => {
        new import_obsidian5.Notice("Note saved");
        return this.app.workspace.openLinkText(
          this.fileHandler.getSafeFilename(fileName),
          "",
          true
        );
      }).catch((error) => {
        console.error(error);
        new import_obsidian5.Notice(`Couldn't save block: ${error.message}`);
      });
    };
    new BlocksModal(this.app, channel, events, onSelectBlock).open();
    void this.arena.getBlocksFromChannel(channel.slug).then((blocks) => {
      events.trigger("blocks-load", blocks);
    }).catch((error) => {
      console.error(error);
      new import_obsidian5.Notice("Couldn't load blocks from that channel.");
    });
  }
  async getBlockByID() {
    new InputModal(this.app, (url) => {
      const blockId = getIDFromURL(url);
      if (blockId === null || blockId <= 0) {
        return "That doesn't look like an are.na block URL or id.";
      }
      return this.arena.getBlockWithID(blockId).then(async (block) => {
        const fileName = `${block.generated_title}`;
        const frontData = Utils_default.getFrontmatterFromBlock(block);
        const content = Utils_default.getBlockContent(block);
        await this.fileHandler.writeFile(
          `${this.settings.folder}`,
          fileName,
          content,
          frontData,
          Utils_default.getDownloadable(block)
        );
        new import_obsidian5.Notice("Note saved");
        await this.app.workspace.openLinkText(
          this.fileHandler.getSafeFilename(fileName),
          "",
          true
        );
        return null;
      }).catch((error) => {
        console.error(error);
        return `Couldn't import that block. Check the id or URL and try again.`;
      });
    }).open();
  }
};

// main.ts
var ArenaManagerPlugin = class extends import_obsidian6.Plugin {
  async onload() {
    await this.loadSettings();
    this.commands = new Commands(this.app, this.settings);
    this.addSettingTab(new ArenaManagerSettingTab(this));
    this.addCommand({
      id: "get-blocks-from-channel",
      name: "Get blocks from channel",
      checkCallback: (checking) => {
        if (Utils_default.hasRequiredSettings(this.settings)) {
          if (!checking) {
            void this.commands.getBlocksFromChannel();
          }
          return true;
        }
        return false;
      }
    });
    this.addCommand({
      id: "pull-block",
      name: "Pull block from Are.na",
      checkCallback: (checking) => {
        const currentFile = this.app.workspace.getActiveFile();
        if (currentFile && Utils_default.hasRequiredSettings(this.settings)) {
          if (!checking) {
            void this.commands.pullBlock();
          }
          return true;
        }
        return false;
      }
    });
    this.addCommand({
      id: "push-note",
      name: "Push note to Are.na",
      checkCallback: (checking) => {
        const currentFile = this.app.workspace.getActiveFile();
        if (currentFile && Utils_default.hasRequiredSettings(this.settings)) {
          if (!checking) {
            void this.commands.pushBlock();
          }
          return true;
        }
        return false;
      }
    });
    this.addCommand({
      id: "get-block-from-arena",
      name: "Get a block from Are.na",
      checkCallback: (checking) => {
        if (Utils_default.hasRequiredSettings(this.settings)) {
          if (!checking) {
            void this.commands.getBlockFromArena();
          }
          return true;
        }
        return false;
      }
    });
    this.addCommand({
      id: "go-to-block",
      name: "Go to block on Are.na",
      checkCallback: (checking) => {
        const currentFile = this.app.workspace.getActiveFile();
        if (currentFile) {
          if (!checking) {
            void this.commands.goToBlock();
          }
          return true;
        }
        return false;
      }
    });
    this.addCommand({
      id: "get-block-by-id",
      name: "Get a block by ID or URL",
      checkCallback: (checking) => {
        if (Utils_default.hasRequiredSettings(this.settings)) {
          if (!checking) {
            void this.commands.getBlockByID();
          }
          return true;
        }
        return false;
      }
    });
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      await this.loadData()
    );
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};

/* nosourcemap */